Feature: Get abstract from the article
  In order to use the abstract text of this article
  as a script 
  I will parse the abstract from the xml file
  
  Scenario Outline: Get the abstract in text format
    Given I have the document <document>
    When I get the abstract
    Then I see the string <abstract>
  
  Examples:
    | document                    | abstract   
    | elife00013.xml              | Bacterially-produced small molecules exert profound influences on animal health, morphogenesis, and evolution through poorly understood mechanisms. In one of the closest living relatives of animals, the choanoflagellate Salpingoeca rosetta, we find that rosette colony development is induced by the prey bacterium Algoriphagus machipongonensis and its close relatives in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1) produced by A. machipongonensis belongs to the small class of sulfonolipids, obscure relatives of the better known sphingolipids that play important roles in signal transmission in plants, animals, and fungi. RIF-1 has extraordinary potency (femtomolar, or 10−15 M) and S. rosetta can respond to it over a broad dynamic range—nine orders of magnitude. This study provides a prototypical example of bacterial sulfonolipids triggering eukaryotic morphogenesis and suggests molecular mechanisms through which bacteria may have contributed to the evolution of animals.
    | elife-kitchen-sink.xml      | Bacterially-produced small molecules exert profound influences on animal health,\n                    morphogenesis, and evolution through poorly understood mechanisms. In one of the\n                    closest living relatives of animals, the choanoflagellate Salpingoeca\n                        rosetta, we find that colony development is induced by the prey\n                    bacterium Algoriphagus machipongonensis and its close relatives\n                    in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1)\n                    produced by A. machipongonensis belongs to the small class of\n                    sulfonolipids, obscure relatives of the better known sphingolipids that play\n                    important roles in signal transmission in plants, animals and fungi. RIF-1 has\n                    extraordinary potency (femtomolar, or 10-15M) and S.\n                        rosetta can respond to it over a broad dynamic range - nine orders\n                    of magnitude. This study provides a prototypical example of bacterial\n                    sulfonolipids triggering eukaryotic morphogenesis and suggests molecular\n                    mechanisms through which bacteria may have contributed to the evolution of\n                    animals.
    | elife_poa_e06828.xml        | RET can be activated in cis or trans by its co-receptors and ligands in vitro, but the physiological roles of trans signaling are unclear. Rapidly adapting (RA) mechanoreceptors in dorsal root ganglia (DRGs) express Ret and the co-receptor Gfrα2 and depend on Ret for survival and central projection growth. Here, we show that Ret and Gfrα2 null mice display comparable early central projection deficits, but Gfrα2 null RA mechanoreceptors recover later. Loss of Gfrα1, the co-receptor implicated in activating RET in trans, causes no significant central projection or cell survival deficit, but Gfrα1;Gfrα2 double nulls phenocopy Ret nulls. Finally, we demonstrate that GFRα1 produced by neighboring DRG neurons activates RET in RA mechanoreceptors. Taken together, our results suggest that trans and cis RET signaling could function in the same developmental process and that the availability of both forms of activation likely enhances but not diversifies outcomes of RET signaling.