Feature: Get abstract from the article
  In order to use the abstract text of this article
  as a script 
  I will parse the abstract from the xml file
  
  Scenario Outline: Get the abstract in text format
    Given I have the document <document>
    When I get the abstract
    Then I see the string <abstract>
  
  Examples:
    | document                    | abstract   
    | elife00013.xml              | Bacterially-produced small molecules exert profound influences on animal health, morphogenesis, and evolution through poorly understood mechanisms. In one of the closest living relatives of animals, the choanoflagellate Salpingoeca rosetta, we find that rosette colony development is induced by the prey bacterium Algoriphagus machipongonensis and its close relatives in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1) produced by A. machipongonensis belongs to the small class of sulfonolipids, obscure relatives of the better known sphingolipids that play important roles in signal transmission in plants, animals, and fungi. RIF-1 has extraordinary potency (femtomolar, or 10−15 M) and S. rosetta can respond to it over a broad dynamic range—nine orders of magnitude. This study provides a prototypical example of bacterial sulfonolipids triggering eukaryotic morphogenesis and suggests molecular mechanisms through which bacteria may have contributed to the evolution of animals.
    | elife-kitchen-sink.xml      | Bacterially-produced small molecules exert profound influences on animal health,\n                    morphogenesis, and evolution through poorly understood mechanisms. In one of the\n                    closest living relatives of animals, the choanoflagellate Salpingoeca\n                        rosetta, we find that colony development is induced by the prey\n                    bacterium Algoriphagus machipongonensis and its close relatives\n                    in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1)\n                    produced by A. machipongonensis belongs to the small class of\n                    sulfonolipids, obscure relatives of the better known sphingolipids that play\n                    important roles in signal transmission in plants, animals and fungi. RIF-1 has\n                    extraordinary potency (femtomolar, or 10-15M) and S.\n                        rosetta can respond to it over a broad dynamic range - nine orders\n                    of magnitude. This study provides a prototypical example of bacterial\n                    sulfonolipids triggering eukaryotic morphogenesis and suggests molecular\n                    mechanisms through which bacteria may have contributed to the evolution of\n                    animals.
    | elife_poa_e06828.xml        | RET can be activated in cis or trans by its co-receptors and ligands in vitro, but the physiological roles of trans signaling are unclear. Rapidly adapting (RA) mechanoreceptors in dorsal root ganglia (DRGs) express Ret and the co-receptor Gfrα2 and depend on Ret for survival and central projection growth. Here, we show that Ret and Gfrα2 null mice display comparable early central projection deficits, but Gfrα2 null RA mechanoreceptors recover later. Loss of Gfrα1, the co-receptor implicated in activating RET in trans, causes no significant central projection or cell survival deficit, but Gfrα1;Gfrα2 double nulls phenocopy Ret nulls. Finally, we demonstrate that GFRα1 produced by neighboring DRG neurons activates RET in RA mechanoreceptors. Taken together, our results suggest that trans and cis RET signaling could function in the same developmental process and that the availability of both forms of activation likely enhances but not diversifies outcomes of RET signaling.
    | elife06003.xml              | Lipids are critical to cellular function and it is generally accepted that lipid turnover is rapid and dysregulation in turnover results in disease (Dawidowicz 1987; Phillips et al., 2009; Liu et al., 2013). In this study, we present an intriguing counter-example by demonstrating that in the center of the human ocular lens, there is no lipid turnover in fiber cells during the entire human lifespan. This discovery, combined with prior demonstration of pronounced changes in the lens lipid composition over a lifetime (Hughes et al., 2012), suggests that some lipid classes break down in the body over several decades, whereas others are stable. Such substantial changes in lens cell membranes may play a role in the genesis of age-related eye disorders. Whether long-lived lipids are present in other tissues is not yet known, but this may prove to be important in understanding the development of age-related diseases.
    
  Scenario Outline: Get the full abstract including inline tags
    Given I have the document <document>
    When I get the full abstract
    Then I see the string <abstract>
    
  Examples:
    | document                    | abstract   
    | elife00013.xml              | Bacterially-produced small molecules exert profound influences on animal health, morphogenesis, and evolution through poorly understood mechanisms. In one of the closest living relatives of animals, the choanoflagellate <italic>Salpingoeca rosetta</italic>, we find that rosette colony development is induced by the prey bacterium <italic>Algoriphagus machipongonensis</italic> and its close relatives in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1) produced by <italic>A. machipongonensis</italic> belongs to the small class of sulfonolipids, obscure relatives of the better known sphingolipids that play important roles in signal transmission in plants, animals, and fungi. RIF-1 has extraordinary potency (femtomolar, or 10<sup>−15</sup> M) and <italic>S. rosetta</italic> can respond to it over a broad dynamic range—nine orders of magnitude. This study provides a prototypical example of bacterial sulfonolipids triggering eukaryotic morphogenesis and suggests molecular mechanisms through which bacteria may have contributed to the evolution of animals.
    | elife-kitchen-sink.xml      | Bacterially-produced small molecules exert profound influences on animal health,\n                    morphogenesis, and evolution through poorly understood mechanisms. In one of the\n                    closest living relatives of animals, the choanoflagellate <italic>Salpingoeca\n                        rosetta</italic>, we find that colony development is induced by the prey\n                    bacterium <italic>Algoriphagus machipongonensis</italic> and its close relatives\n                    in the Bacteroidetes phylum. Here we show that a rosette inducing factor (RIF-1)\n                    produced by <italic>A. machipongonensis</italic> belongs to the small class of\n                    sulfonolipids, obscure relatives of the better known sphingolipids that play\n                    important roles in signal transmission in plants, animals and fungi. RIF-1 has\n                    extraordinary potency (femtomolar, or 10<sup>-15</sup>M) and <italic>S.\n                        rosetta</italic> can respond to it over a broad dynamic range - nine orders\n                    of magnitude. This study provides a prototypical example of bacterial\n                    sulfonolipids triggering eukaryotic morphogenesis and suggests molecular\n                    mechanisms through which bacteria may have contributed to the evolution of\n                    animals.
    | elife_poa_e06828.xml        | RET can be activated in <italic>cis</italic> or <italic>trans</italic> by its co-receptors and ligands <italic>in vitro</italic>, but the physiological roles of <italic>trans</italic> signaling are unclear. Rapidly adapting (RA) mechanoreceptors in dorsal root ganglia (DRGs) express <italic>Ret</italic> and the co-receptor <italic>Gfrα2</italic> and depend on <italic>Ret</italic> for survival and central projection growth. Here, we show that <italic>Ret</italic> and <italic>Gfrα2</italic> null mice display comparable early central projection deficits, but <italic>Gfrα2</italic> null RA mechanoreceptors recover later. Loss of <italic>Gfrα1</italic>, the co-receptor implicated in activating RET <italic>in trans</italic>, causes no significant central projection or cell survival deficit, but <italic>Gfrα1;Gfrα2</italic> double nulls phenocopy <italic>Ret</italic> nulls. Finally, we demonstrate that GFRα1 produced by neighboring DRG neurons activates RET in RA mechanoreceptors. Taken together, our results suggest that <italic>trans</italic> and <italic>cis</italic> RET signaling could function in the same developmental process and that the availability of both forms of activation likely enhances but not diversifies outcomes of RET signaling.
    | elife06003.xml              | Lipids are critical to cellular function and it is generally accepted that lipid turnover is rapid and dysregulation in turnover results in disease (<xref ref-type="bibr" rid="bib7">Dawidowicz 1987</xref>; <xref ref-type="bibr" rid="bib24">Phillips et al., 2009</xref>; <xref ref-type="bibr" rid="bib20">Liu et al., 2013</xref>). In this study, we present an intriguing counter-example by demonstrating that in the center of the human ocular lens, there is no lipid turnover in fiber cells during the entire human lifespan. This discovery, combined with prior demonstration of pronounced changes in the lens lipid composition over a lifetime (<xref ref-type="bibr" rid="bib16">Hughes et al., 2012</xref>), suggests that some lipid classes break down in the body over several decades, whereas others are stable. Such substantial changes in lens cell membranes may play a role in the genesis of age-related eye disorders. Whether long-lived lipids are present in other tissues is not yet known, but this may prove to be important in understanding the development of age-related diseases.
    
  Scenario Outline: Get the full exective summary abstract or digest including inline tags
    Given I have the document <document>
    When I get the digest
    Then I see the string <digest>
  
  Examples:
    | document                    | digest   
    | elife00013.xml              | All animals, including humans, evolved in a world filled with bacteria. Although bacteria are most familiar as pathogens, some bacteria produce small molecules that are essential for the biology of animals and other eukaryotes, although the details of the ways in which these bacterial molecules are beneficial are not well understood. The choanoflagellates are water-dwelling organisms that use their whip-like flagella to move around, feeding on bacteria. They can exist as one cell or a colony of multiple cells and, perhaps surprisingly, are the closest known living relatives of animals. This means that experiments on these organisms have the potential to improve our understanding of animal development and the transition from egg to embryo to adult. Alegado et al. have explored how the morphology of Salpingoeca rosetta, a colony-forming choanoflagellate, is influenced by its interactions with various species of bacteria. In particular, they find that the development of multicellularity in S. rosetta is triggered by the presence of the bacterium Algoriphagus machipongonensis as well as its close relatives. They also identify the signaling molecule produced by the bacteria to be C32H64NO7S; this lipid molecule is an obscure relative of the sphingolipid molecules that have important roles in signal transmission in animals, plants, and fungi. Moreover, Alegado et al. show that S. rosetta can respond to this molecule – which they call rosette-inducing factor (RIF-1) – over a wide range of concentrations, including concentrations as low as 10−17 M. The work of Alegado et al. suggests that interactions between S. rosetta and Algoriphagus bacteria could be a productive model system for studying the influences of bacteria on animal cell biology, and for investigating the mechanisms of signal delivery and reception. Moreover, the molecular mechanisms revealed by this work leave open the possibility that bacteria might have contributed to the evolution of multicellularity in animals.
    | elife-kitchen-sink.xml      | Humans and other animals evolved in a world filled with bacteria, and bacteria\n                    have influenced the evolution of animals and humans. Although bacteria are most\n                    familiar as pathogens, they also produce small molecules that animals and other\n                    eukaryotes need, although the details of these beneficial effects are not well\n                    understood. The choanoflagellates are water-dwelling organisms that use their whip-like\n                    flagella to move around, feeding on bacteria. They can exist as one cell or a\n                    colony of multiple cells and, perhaps surprisingly, are the closest known living\n                    relatives of animals. This means that experiments on these organisms have the\n                    potential to improve our understanding of animal development and the transition\n                    from egg to embryo to adult. Alegado et al. have explored how the morphology of\n                        Salpingoeca rosetta, a colony-forming choanoflagellate, is\n                    influenced by its interactions with various species of bacteria. In particular,\n                    they find that the development of multicellularity in S.\n                        rosettais triggered by the presence of the bacterium\n                        Algoriphagus machipongonensis as well as its close\n                    relatives. They also identify the signaling molecule produced by the bacteria to\n                    be C32H64NO7S; this lipid molecule is an\n                    obscure relative of the sphingolipid molecules that have important roles in\n                    signal transmission in animals, plants, and fungi. Moreover, Alegado et\n                        al. show that S. rosetta can respond to this\n                    molecule - which they call rosette-inducing factor (RIF-1) - over a wide range\n                    of concentrations, including concentrations as low as 10-17M. The work of Alegado et al. suggests that interactions between\n                        S. rosetta and Algoriphagus bacteria could\n                    be a productive model system for studying the influences of bacteria on animal\n                    cell biology and for investigating the mechanisms of signal delivery and\n                    reception. Moreover, the molecular mechanisms revealed by this work leave open\n                    the possibility that bacteria might have contributed to the evolution of\n                    multicellularity in animals.
    | elife_poa_e06828.xml        | None
    
    
  Scenario Outline: Get the exective summary abstract or digest in text format
    Given I have the document <document>
    When I get the full digest
    Then I see the string <digest>
  
  Examples:
    | document                    | digest   
    | elife00013.xml              | All animals, including humans, evolved in a world filled with bacteria. Although bacteria are most familiar as pathogens, some bacteria produce small molecules that are essential for the biology of animals and other eukaryotes, although the details of the ways in which these bacterial molecules are beneficial are not well understood. The choanoflagellates are water-dwelling organisms that use their whip-like flagella to move around, feeding on bacteria. They can exist as one cell or a colony of multiple cells and, perhaps surprisingly, are the closest known living relatives of animals. This means that experiments on these organisms have the potential to improve our understanding of animal development and the transition from egg to embryo to adult. Alegado <italic>et al</italic>. have explored how the morphology of <italic>Salpingoeca rosetta,</italic> a colony-forming choanoflagellate, is influenced by its interactions with various species of bacteria. In particular, they find that the development of multicellularity in <italic>S. rosetta</italic> is triggered by the presence of the bacterium <italic>Algoriphagus machipongonensis</italic> as well as its close relatives. They also identify the signaling molecule produced by the bacteria to be C<sub>32</sub>H<sub>64</sub>NO<sub>7</sub>S; this lipid molecule is an obscure relative of the sphingolipid molecules that have important roles in signal transmission in animals, plants, and fungi. Moreover, Alegado <italic>et al</italic>. show that <italic>S. rosetta</italic> can respond to this molecule – which they call rosette-inducing factor (RIF-1) – over a wide range of concentrations, including concentrations as low as 10<sup>−17</sup> M. The work of Alegado <italic>et al</italic>. suggests that interactions between <italic>S. rosetta</italic> and <italic>Algoriphagus</italic> bacteria could be a productive model system for studying the influences of bacteria on animal cell biology, and for investigating the mechanisms of signal delivery and reception. Moreover, the molecular mechanisms revealed by this work leave open the possibility that bacteria might have contributed to the evolution of multicellularity in animals.
    | elife-kitchen-sink.xml      | Humans and other animals evolved in a world filled with bacteria, and bacteria\n                    have influenced the evolution of animals and humans. Although bacteria are most\n                    familiar as pathogens, they also produce small molecules that animals and other\n                    eukaryotes need, although the details of these beneficial effects are not well\n                    understood. The choanoflagellates are water-dwelling organisms that use their whip-like\n                    flagella to move around, feeding on bacteria. They can exist as one cell or a\n                    colony of multiple cells and, perhaps surprisingly, are the closest known living\n                    relatives of animals. This means that experiments on these organisms have the\n                    potential to improve our understanding of animal development and the transition\n                    from egg to embryo to adult. Alegado <italic>et al.</italic> have explored how the morphology of\n                        <italic>Salpingoeca rosetta,</italic> a colony-forming choanoflagellate, is\n                    influenced by its interactions with various species of bacteria. In particular,\n                    they find that the development of multicellularity in <italic>S.\n                        rosetta</italic>is triggered by the presence of the bacterium\n                        <italic>Algoriphagus machipongonensis</italic> as well as its close\n                    relatives. They also identify the signaling molecule produced by the bacteria to\n                    be C<sub>32</sub>H<sub>64</sub>NO<sub>7</sub>S; this lipid molecule is an\n                    obscure relative of the sphingolipid molecules that have important roles in\n                    signal transmission in animals, plants, and fungi. Moreover, Alegado <italic>et\n                        al.</italic> show that <italic>S. rosetta</italic> can respond to this\n                    molecule - which they call rosette-inducing factor (RIF-1) - over a wide range\n                    of concentrations, including concentrations as low as 10<sup>-17</sup>M. The work of Alegado <italic>et al.</italic> suggests that interactions between\n                        <italic>S. rosetta</italic> and <italic>Algoriphagus</italic> bacteria could\n                    be a productive model system for studying the influences of bacteria on animal\n                    cell biology and for investigating the mechanisms of signal delivery and\n                    reception. Moreover, the molecular mechanisms revealed by this work leave open\n                    the possibility that bacteria might have contributed to the evolution of\n                    multicellularity in animals.
    | elife_poa_e06828.xml        | None
    